alias gs="git status"
alias gl="git log"
alias cl="clear"
alias gclone='git clone'
alias gcl=gclone
alias gdiff='git diff'
alias gd=gdiff
alias gcheck='git checkout'
alias gch=gcheck
alias teleq='telepresence quit -s'
alias telec='telepresence connect'
alias telecv='telepresence connect --proxy-via all=traffic-manager-ambassador-agent'
alias tcv=telecv
alias tq=teleq
alias tc=telec
alias tqc='tq && tc'
alias ks='kubecm switch'
alias ks67='kubecm switch 67.master'
alias ks671='kubecm switch 67.database1'
alias ks672='kubecm switch 67.database2'
alias hgrep='history | grep'
alias hg=hgrep
alias uu='uuidgen | pbcopy'
alias zshrc='vim ~/.zshrc'
alias sz='source ~/.zshrc'
alias tm='tmux'
alias vimrc='vim ~/.vimrc'
alias sv='source ~/.vimrc'
alias gmt='go mod tidy'
alias svim='sudo vim'
alias sv=svim
alias diff='colordiff'
alias lgrep='ls | grep'
alias lg=lgrep
alias tidb='sh ~/Code/scripts/tidb.sh'
alias copy='sh ~/Code/scripts/copy_file.sh'
alias ch777='chmod 777'
